# action.yml
name: "Deploy Mautic to Selectel"
description: "Deploy Mautic with Docker Compose to a Selectel VPS with automated SSL and monitoring"
author: "MautiBox"

branding:
  icon: "cloud"
  color: "blue"

inputs:
  # --- Selectel configuration---
  selectel-token:
    description: "Selectel API access token (X-Token)"
    required: true
  ssh-private-key:
    description: "SSH private key for VPS access"
    required: true
  github-token:
    description: "GitHub Personal Access Token (PAT) for accessing private repositories for themes, plugins, and language packs."
    required: false

  # --- Конфигурация Mautic ---
  email:
    description: "Admin email address for Mautic and SSL certificates"
    required: true
  mautic-password:
    description: "Admin password for Mautic"
    required: true
  mautic-version:
    description: "Mautic Docker image version"
    required: false
    default: "6.0.5-apache"
  mautic-port:
    description: "Port for Mautic instance"
    required: false
    default: "8001"

  # --- Языковой пакет Mautic ---
  language-pack-url:
    description: "URL to the language pack ZIP file (e.g., from a GitHub release)."
    required: false
    default: "https://github.com/zaharovrd/language-packs/raw/master/mautibox_ru.zip"
  locale:
    description: "The language code to set as default during installation (e.g., ru, es)."
    required: false
    default: "ru"
  default-timezone:
    description: "Default timezone for Mautic installation (e.g., Europe/Moscow)."
    required: false
    default: "Europe/Moscow"

  # --- Конфигурация VPS ---
  domain:
    description: "Domain name for your Mautic instance (optional, will use IP if not provided)"
    required: false
  vps-name:
    description: "Name for the Selectel scalet (server)"
    required: false
    default: "mautic-vps"
  vps-rplan:
    description: "Selectel server plan (e.g., small, medium, large)"
    required: false
    default: "medium"
  vps-location:
    description: "Selectel location (e.g., spb0, msk1)"
    required: false
    default: "spb0"

  # --- Плагины и темы Mautic ---
  themes:
    description: |
      List of Mautic theme packages from Packagist or GitHub (one per line).

      Packagist packages:
      vendor/theme-name:^1.0
      another-vendor/custom-theme:dev-main

      GitHub URLs (public repositories):
      https://github.com/user/theme-repo/archive/refs/heads/main.zip

      GitHub URLs with custom directory and authentication:
      https://github.com/company/private-theme/archive/main.zip?directory=MyCustomTheme&token=ghp_xxxxxxxxxxxxxxxxxxxx
      https://github.com/vendor/premium-theme/archive/v2.1.0.zip?directory=PremiumTheme&token=ghp_yyyyyyyyyyyyyyyyyyyy
    required: false

  plugins:
    description: |
      List of Mautic plugin packages from Packagist or GitHub (one per line).

      Packagist packages:
      vendor/plugin-name:^2.0
      another-vendor/custom-plugin:^1.5

      GitHub URLs (public repositories):
      https://github.com/user/plugin-repo/archive/refs/heads/main.zip

      GitHub URLs with custom directory and authentication:
      https://github.com/company/private-plugin/archive/main.zip?directory=CompanyPlugin&token=ghp_xxxxxxxxxxxxxxxxxxxx
      https://github.com/vendor/premium-plugin/archive/v2.1.0.zip?directory=PremiumPlugin&token=ghp_yyyyyyyyyyyyyyyyyyyy

    required: false

  # --- Конфигурация Базы Данных ---
  mysql-database:
    description: "MySQL database name"
    required: false
    default: "mautic_db"
  mysql-user:
    description: "MySQL user name"
    required: false
    default: "mautic_db_user"
  mysql-password:
    description: "MySQL password"
    required: true
  mysql-root-password:
    description: "MySQL root password"
    required: true

outputs:
  vps-ip:
    description: "IP address of the created VPS"
    value: ${{ steps.deploy.outputs.vps-ip }}
  mautic-url:
    description: "URL to access your Mautic instance"
    value: ${{ steps.deploy.outputs.mautic-url }}
  deployment-log:
    description: "Path to the deployment log artifact"
    value: ${{ steps.deploy.outputs.deployment-log }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        echo "🔍 Validating required inputs..."
        if [ -z "${{ inputs.selectel-token }}" ]; then
          echo "❌ Error: selectel-token is required"
          exit 1
        fi
        if [ -z "${{ inputs.ssh-private-key }}" ]; then
          echo "❌ Error: ssh-private-key is required"
          exit 1
        fi
        if [ -z "${{ inputs.email }}" ]; then
          echo "❌ Error: email is required"
          exit 1
        fi
        if [ -z "${{ inputs.mautic-password }}" ]; then
          echo "❌ Error: mautic-password is required"
          exit 1
        fi
        if [ -z "${{ inputs.mysql-password }}" ]; then
          echo "❌ Error: mysql-password is required"
          exit 1
        fi
        if [ -z "${{ inputs.mysql-root-password }}" ]; then
          echo "❌ Error: mysql-root-password is required"
          exit 1
        fi
        echo "✅ All required inputs validated"

    - name: Create and configure VPS on Selectel
      id: deploy
      shell: bash
      # Указываем наш новый скрипт для Selectel
      run: |
        echo "Debug URL from input: ${{ inputs.language-pack-url }}"
        ${{ github.action_path }}/scripts/deploy_selectel.sh
      env:
        # Передаем все inputs как переменные окружения в скрипт
        INPUT_SELECTEL_TOKEN: ${{ inputs.selectel-token }}
        INPUT_SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_EMAIL: ${{ inputs.email }}
        INPUT_MAUTIC_PASSWORD: ${{ inputs.mautic-password }}
        INPUT_MAUTIC_VERSION: ${{ inputs.mautic-version }}
        INPUT_MAUTIC_PORT: ${{ inputs.mautic-port }}
        INPUT_LANGUAGE_PACK_URL: ${{ inputs.language-pack-url }}
        INPUT_LOCALE: ${{ inputs.locale }}
        INPUT_DOMAIN: ${{ inputs.domain }}
        INPUT_VPS_NAME: ${{ inputs.vps-name }}
        INPUT_VPS_RPLAN: ${{ inputs.vps-rplan }}
        INPUT_VPS_LOCATION: ${{ inputs.vps-location }}
        INPUT_THEMES: ${{ inputs.themes }}
        INPUT_PLUGINS: ${{ inputs.plugins }}
        INPUT_MYSQL_DATABASE: ${{ inputs.mysql-database }}
        INPUT_MYSQL_USER: ${{ inputs.mysql-user }}
        INPUT_MYSQL_PASSWORD: ${{ inputs.mysql-password }}
        INPUT_MYSQL_ROOT_PASSWORD: ${{ inputs.mysql-root-password }}
        ACTION_PATH: ${{ github.action_path }}

    - name: Upload deployment log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mautic-deployment-log
        # Убедимся, что путь к логу правильный, он создается в корне рабочего пространства
        path: ./setup-dc.log

    - name: Cleanup
      shell: bash
      if: always()
      run: |
        echo "🧹 Cleaning up SSH keys and temporary files..."
        rm -f ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
        echo "✅ Cleanup completed"
